# Generated by Django 4.2.27 on 2026-01-06 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabase_user_id', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('partner', 'Partner'), ('admin', 'Admin')], default='farmer', max_length=10)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_weight', models.IntegerField(default=20)),
                ('activity_frequency_weight', models.IntegerField(default=50)),
                ('consistency_weight', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('main_crop', models.CharField(blank=True, max_length=100, null=True)),
                ('farm_size', models.CharField(blank=True, max_length=100, null=True)),
                ('trust_level', models.CharField(default='New', max_length=50)),
                ('internal_score', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sync_status', models.CharField(default='synced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.farmerprofile')),
            ],
            options={
                'verbose_name_plural': 'Farm Activities',
            },
        ),
    ]
